In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('output_adam.csv')

In [10]:
df.head(10)

,frame.number,frame.len,frame.time,frame.time_epoch,frame.protocols,eth.src,eth.dst,eth.type,ip.src,ip.dst,...,pop.response,imap.request.command,imap.response,ftp.request.command,ftp.request.arg,ftp.response.code,ftp.response.arg,ipv6.src,ipv6.dst,ipv6.plen
0,1,60,"Oct 25, 2018 07:46:22.933899000 CEST",1.540446e+09,eth:ethertype:ip:tcp,5c:cf:7f:05:f2:c6,4c:09:d4:c6:12:7b,0x0800,192.168.2.108,52.24.43.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,60,"Oct 25, 2018 07:46:22.933904000 CEST",1.540446e+09,eth:ethertype:ip:tcp,5c:cf:7f:05:f2:c6,4c:09:d4:c6:12:7b,0x0800,192.168.2.108,52.25.66.250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,86,"Oct 25, 2018 07:46:22.934426000 CEST",1.540446e+09,eth:ethertype:ip:icmp:ip:tcp,4c:09:d4:c6:12:7b,5c:cf:7f:05:f2:c6,0x0800,192.168.2.1,192.168.2.108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86,"Oct 25, 2018 07:46:22.934636000 CEST",1.540446e+09,eth:ethertype:ip:icmp:ip:tcp,4c:09:d4:c6:12:7b,5c:cf:7f:05:f2:c6,0x0800,192.168.2.1,192.168.2.108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,60,"Oct 25, 2018 07:46:23.291054000 CEST",1.540446e+09,eth:ethertype:arp,48:02:2e:01:83:15,ff:ff:ff:ff:ff:ff,0x0806,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,74,"Oct 25, 2018 07:46:23.367591000 CEST",1.540446e+09,eth:ethertype:ip:icmp:data,40:8d:5c:4b:99:1d,3c:33:00:98:ee:fd,0x0800,192.168.2.101,192.168.2.110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,74,"Oct 25, 2018 07:46:23.383526000 CEST",1.540446e+09,eth:ethertype:ip:icmp:data,3c:33:00:98:ee:fd,40:8d:5c:4b:99:1d,0x0800,192.168.2.110,192.168.2.101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,117,"Oct 25, 2018 07:46:23.391651000 CEST",1.540446e+09,eth:ethertype:ip:udp:dns,00:16:6c:7f:82:20,4c:09:d4:c6:12:7b,0x0800,192.168.2.115,192.168.2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,117,"Oct 25, 2018 07:46:23.393709000 CEST",1.540446e+09,eth:ethertype:ip:udp:dns,4c:09:d4:c6:12:7b,00:16:6c:7f:82:20,0x0800,192.168.2.1,192.168.2.115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,60,"Oct 25, 2018 07:46:23.435821000 CEST",1.540446e+09,eth:ethertype:ip:tcp,5c:cf:7f:05:f2:c6,4c:09:d4:c6:12:7b,0x0800,192.168.2.108,52.24.43.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df['frame.time'] = df['frame.time'].str.replace("Central European Summer Time", "", regex=False)

In [12]:
df['frame.time'] = pd.to_datetime(df['frame.time'])

/tmp/ipykernel_4710/2446345425.py:1: FutureWarning: Parsing 'CEST' as tzlocal (dependent on system timezone) is deprecated and will raise in a future version. Pass the 'tz' keyword or call tz_localize after construction instead
  df['frame.time'] = pd.to_datetime(df['frame.time'])
/tmp/ipykernel_4710/2446345425.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['frame.time'] = pd.to_datetime(df['frame.time'])

AttributeError: 'NoneType' object has no attribute 'total_seconds'

In [13]:
df["ip.src"].value_counts()

ip.src
192.168.2.108    51747
192.168.2.1      35416
192.168.2.113    34805
192.168.2.110    23554
192.168.2.115    13486
192.168.2.112     9395
192.168.2.101     8688
192.168.2.109     5771
192.168.2.104     4390
192.168.2.107     1896
192.168.2.118     1722
192.168.2.103     1624
192.168.2.126     1415
192.168.2.111      744
192.168.2.121      739
192.168.2.122      733
192.168.2.119      445
192.168.2.120      404
192.168.2.105      391
192.168.2.196      270
192.168.2.117       39
0.0.0.0             27
Name: count, dtype: int64

## Poniżej komenda do użycia w terminalu w pliku gdzie masz PCAP

In [ ]:
#tshark -r attack-simulation.pcap -T fields  -E header=y -E separator=, -E quote=d -E occurrence=f  -e frame.number  -e frame.len  -e frame.time  -e frame.time_epoch  -e frame.protocols  -e eth.src  -e eth.dst  -e eth.type  -e ip.src  -e ip.dst  -e ip.len  -e ip.ttl  -e ip.flags  -e ip.frag_offset  -e ip.proto  -e ip.version  -e ip.dsfield  -e ip.checksum  -e tcp.srcport  -e tcp.dstport  -e tcp.len  -e tcp.seq  -e tcp.ack  -e tcp.flags  -e tcp.flags.syn  -e tcp.flags.ack  -e tcp.flags.fin  -e tcp.flags.reset  -e tcp.window_size  -e tcp.checksum  -e tcp.stream  -e udp.srcport  -e udp.dstport  -e udp.length  -e udp.checksum  -e icmp.type  -e icmp.code  -e icmp.checksum  -e http.request.method  -e http.request.uri  -e http.request.version  -e http.request.full_uri  -e http.response.code  -e http.user_agent  -e http.content_length_header  -e http.content_type  -e http.cookie  -e http.host  -e http.referer  -e http.location  -e http.authorization  -e http.connection  -e dns.qry.name  -e dns.qry.type  -e dns.qry.class  -e dns.flags.response  -e dns.flags.recdesired  -e dns.flags.rcode  -e dns.resp.ttl  -e dns.resp.len  -e smtp.req.command  -e smtp.data.fragment  -e pop.request.command  -e pop.response  -e imap.request.command  -e imap.response  -e ftp.request.command  -e ftp.request.arg  -e ftp.response.code  -e ftp.response.arg  -e ipv6.src  -e ipv6.dst  -e ipv6.plen  > output_adam.csv